"""ProductMovement

Revision ID: f405f9471bef
Revises: 26ebeab73f2a
Create Date: 2021-12-22 22:28:51.863640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f405f9471bef'
down_revision = '26ebeab73f2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_movement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fromLocation', sa.Integer(), nullable=True),
    sa.Column('toLocation', sa.Integer(), nullable=True),
    sa.Column('productId', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_movement')
    # ### end Alembic commands ###
